### ISSUE TITLE
Can’t withdraw KNC from Kyber Staking!

### ISSUE THREAD

**Issue by metbtood** [KyberNetwork/developer-portal#145]
0xecf0bdb7b3f349abfd68c3563678124c5e8aaea3

Can someone help me! I payed already a lot of ETH to withdraw but the error is still the same!! Transaction Fail!

One of the transactions:

0xfdb216305ba351eaee08e23ac2656b095fea2e345e7c02fd5652822aa1481b17

Thanks in advance!!

**Comment by Anyhowclick** [comment]
Hi, seems like your txns run out of gas. Kindly increase the gas limit (maybe 200k?), should work.

**Comment by metbtood** [comment]
Thanks, will Roy!

**Comment by metbtood** [comment]
Thanks, will try it!
