### ISSUE TITLE
I couldn't withdraw my knc from kyber.org to my metamask wallet.

### ISSUE THREAD

**Issue by Phamkiet123** [KyberNetwork/developer-portal#150]
Hello,

My wallet is 0x80Aa51d8Bef888153fA3158A61D7ed26D06B78B1

My withdrawal transaction: 0x097eb3b1781adbe5ae29659e172e3aad05e4b71b3f3b85ee3010f1d3eb945b8f

It said out of gas and the transaction fell.

Please give me an advise how can I withdraw my KNC.
Thanks.

**Comment by Anyhowclick** [comment]
Hi there,
You can try increase the gas limit to about 300k.

**Comment by ayobuenavista** [comment]
> Hello,
> 
> My wallet is 0x80Aa51d8Bef888153fA3158A61D7ed26D06B78B1
> 
> My withdrawal transaction: 0x097eb3b1781adbe5ae29659e172e3aad05e4b71b3f3b85ee3010f1d3eb945b8f
> 
> It said out of gas and the transaction fell.
> 
> Please give me an advise how can I withdraw my KNC.
> Thanks.

Closing this as this is not related to the developer portal. Please seek support from the Kyber discord group (https://discord.gg/NfFMVz6).
